name: "Lab Data dan Komputasi Geoteknik"
description: "Official web page of Lab Data dan Komputasi Geoteknik, Institut Teknologi Bandung."

url: "lab-datageo.github.io"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        members:
                output: true
        publications:
                output: true
        projects:
                output: true
        research_themes:
                output: false
        funded_projects:
                output: false
        student_research:
                output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
